In [3]:
import numpy as np
tableau1=np.array([ 1,5,7,8])
tableau1

array([1, 5, 7, 8])

In [4]:
#tableau2=np.array([1,2,3,4,5,6,7,8,9])
#tableau2
tableau2=np.arange(1,10)
tableau2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
## 3. Créer un tableau de 10 éléments rempli de 0
table=np.zeros(10, dtype="int")
table
#table=np.full(10,0)
#table

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#4. Créer un tableau de 2 lignes 5 colonnes rempli de 0
#table1=np.full((2,5),0)
table1=np.zeros((2,5))
table1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
#5. Créer un tableau de 10 éléments rempli de 1
table2=np.ones(10)
table2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
#6. Créer un tableau de 2 lignes 5 colonnes rempli de 1
table3=np.ones((2,5))
table3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
#7. Créer un tableau de 10 éléments rempli 8.5
table4=np.full((1,10),8.5)
table4

array([[8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5]])

In [10]:
#8. Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus
tableS=np.array(range(1,10))
tableS

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#9. Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs allant de 1 à 9 inclus
#tables1=np.array([[1,2,3],[4,5,6],[7,8,9]])
tables1=np.arange(1,10).reshape(3,3)
tables1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#10.Créer une matrice identité de 4 lignes 4 colonnes
matricei =np.identity(4)
matricei

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#11. Tableau rempli de valeurs aléatoires normales centrées en zéro
tableB=np.linspace(-5,5,5)
tableB

array([-5. , -2.5,  0. ,  2.5,  5. ])

In [14]:
#12.Créer un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et
10
tableauA=np.random.randint(2,10,size=20)
tableauA

array([8, 8, 9, 2, 2, 2, 3, 8, 3, 7, 3, 4, 4, 3, 8, 7, 6, 8, 3, 8])

In [15]:
#13.Transformer le tableau précédent en matrice de 4 lignes et 5 colonnes
matrice=tableauA.reshape((4,5))
matrice

array([[8, 8, 9, 2, 2],
       [2, 3, 8, 3, 7],
       [3, 4, 4, 3, 8],
       [7, 6, 8, 3, 8]])

In [16]:
#14.Créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude égale
tab=np.linspace(0,1,5)
tab

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
type =tab.dtype
type

dtype('float64')

EXERCICE2

In [18]:
#1. Afficher le nombre de lignes et de colonnes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [19]:
#2. Afficher la dimension de mon tableau
a.ndim

2

In [20]:
#3. Afficher le nombre d'élément de mon tableau
a.size

9

In [21]:
#4. Afficher le type des éléments du tableau
a.dtype

dtype('int32')

EXERCICE3

In [22]:
#1. afficher la valeur 5 qui est dans le tableau
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[1,1])

5


In [23]:
#2. Remplacer le 5 qui est dans le tableau par 0
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[b ==5 ] = 0
b

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [24]:
#3. afficher les chiffres 3, 6 et 9 du tableau
print(b[0,2])
print(b[1,2])
print(b[2,2])

3
6
9


In [25]:
#4. créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiersaléatoires compris entre 0 et 9
import random
F= np.random.randint(9,size = (4,3))
F


array([[5, 1, 5],
       [5, 4, 8],
       [8, 6, 6],
       [7, 3, 7]])

In [26]:
type=F.dtype
type

dtype('int32')

In [42]:
#5. Vérifier qu’il y a des nombres inférieur à 5
F<5


array([[False,  True, False],
       [False,  True, False],
       [False, False, False],
       [False,  True, False]])

In [43]:
#6. Remplacer les nombres inférieurs à 5 par 0
F[F<5]=0
F

array([[5, 0, 5],
       [5, 0, 8],
       [8, 6, 6],
       [7, 0, 7]])

EXERCICE4

In [72]:
#1. Créer un tableau rempli de 11 nombres entiersaléatoires compris entre 0 et 9
T=np.random.randint(0,9,11)
T

array([5, 0, 2, 2, 5, 8, 8, 5, 4, 7, 3])

In [73]:
#2. Quel est le type des éléments du tableau ?
type=T.dtype
type

dtype('int32')

In [74]:
#3. Changer de type des éléments du tableau en float32
T=T.astype('float32')
T

array([5., 0., 2., 2., 5., 8., 8., 5., 4., 7., 3.], dtype=float32)

In [75]:
T.ndim

1

In [76]:
type=T.dtype
type

dtype('float32')

In [77]:
#4. Ajouter le chiffre 3 à la fin du tableau à une dimension
T=np.append(T,3)
T

array([5., 0., 2., 2., 5., 8., 8., 5., 4., 7., 3., 3.])

In [78]:
#5. Transformer le tableau en matrice dénommée “Te” de 3 lignes et 4 colonnes
Te = T.reshape(3,4)
Te

array([[5., 0., 2., 2.],
       [5., 8., 8., 5.],
       [4., 7., 3., 3.]])

In [80]:
#6. Créer une matrice dénommée “b” de 3 lignes et 4 colonnes remplie de séried'entiers successifs allant de 1 à 12 inclus
b=np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
#7. Créer une matrice dénommée “c” qui est la concaténation des deux tableaux“Te” et “b” dans le sens horizontale
c=np.concatenate((Te,b))
#c=np.hstack((Te,b))
c

array([[ 5.,  0.,  2.,  2.,  1.,  2.,  3.,  4.],
       [ 5.,  8.,  8.,  5.,  5.,  6.,  7.,  8.],
       [ 4.,  7.,  3.,  3.,  9., 10., 11., 12.]])

In [89]:
#8. Créer une matrice dénommée “d” qui est la concaténation des deux tableaux“T” et “b” dans le sens vertical
d=np.vstack((Te,b))
d

array([[ 5.,  0.,  2.,  2.],
       [ 5.,  8.,  8.,  5.],
       [ 4.,  7.,  3.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [91]:
#9. Aplatir un tableau “d”
d=d.ravel()
d

array([ 5.,  0.,  2.,  2.,  5.,  8.,  8.,  5.,  4.,  7.,  3.,  3.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [92]:
#10.Supprimer dernier élément du tableau
d=np.delete(d,-1)
d

array([ 5.,  0.,  2.,  2.,  5.,  8.,  8.,  5.,  4.,  7.,  3.,  3.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

EXERCICE5

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#1. Afficher la somme des éléments du tableau
np.sum(a)

45

In [6]:
#2. Afficher la somme des éléments du tableau par colonne
np.sum(a,axis=0)

array([12, 15, 18])

In [7]:
#3. Afficher la somme des éléments du tableau par ligne
np.sum(a,axis=1)

array([ 6, 15, 24])

In [8]:
#4. Afficher le produit des éléments du tableau par colonne
np.prod(a,axis=0)

array([ 28,  80, 162])

In [9]:
#5. Afficher le minimum du tableau
np.min(a)

1

In [10]:
#6. Afficher le maximum des éléments du tableau
np.max(a)

9

In [11]:
#7. Afficher la moyenne des éléments du tableau
np.mean(a)

5.0

In [12]:
#8. Afficher la variance des éléments du tableau
np.var(a)

6.666666666666667

In [123]:
#9. Afficher l’écart type des éléments du tableau
np.std(a)

2.581988897471611